// Popular anime Chinese title mappings
// Key: lowercase romaji or English title, Value: Chinese title

const TITLE_MAP: Record<string, string> = {
  "one piece": "海贼王",
  "naruto": "火影忍者",
  "naruto shippuuden": "火影忍者疾风传",
  "naruto shippuden": "火影忍者疾风传",
  "boruto: naruto next generations": "博人传",
  "boruto": "博人传",
  "bleach": "死神",
  "bleach: thousand-year blood war": "死神：千年血战篇",
  "bleach: thousand-year blood war - the conflict": "死神：千年血战篇 相克谭",
  "dragon ball": "龙珠",
  "dragon ball super": "龙珠超",
  "dragon ball z": "龙珠Z",
  "dragon ball daima": "龙珠DAIMA",
  "hunter x hunter": "全职猎人",
  "hunter × hunter": "全职猎人",
  "fullmetal alchemist": "钢之炼金术师",
  "fullmetal alchemist: brotherhood": "钢之炼金术师FA",
  "fairy tail": "妖精的尾巴",
  "fairy tail: 100 years quest": "妖精的尾巴 百年任务",
  "detective conan": "名侦探柯南",
  "meitantei conan": "名侦探柯南",
  "gintama": "银魂",
  "gintama.": "银魂",
  "jojo's bizarre adventure": "JOJO的奇妙冒险",
  "jojo no kimyou na bouken": "JOJO的奇妙冒险",
  "jojo's bizarre adventure: stone ocean": "JOJO的奇妙冒险 石之海",
  "jojo's bizarre adventure: golden wind": "JOJO的奇妙冒险 黄金之风",
  "jojo's bizarre adventure: diamond is unbreakable": "JOJO的奇妙冒险 不灭钻石",
  "jojo's bizarre adventure: stardust crusaders": "JOJO的奇妙冒险 星尘斗士",
  "kimetsu no yaiba": "鬼灭之刃",
  "demon slayer": "鬼灭之刃",
  "kimetsu no yaiba: mugen train": "鬼灭之刃：无限列车篇",
  "kimetsu no yaiba: entertainment district arc": "鬼灭之刃：游郭篇",
  "kimetsu no yaiba: swordsmith village arc": "鬼灭之刃：刀匠村篇",
  "kimetsu no yaiba: hashira training arc": "鬼灭之刃：柱训练篇",
  "demon slayer: kimetsu no yaiba": "鬼灭之刃",
  "demon slayer: mugen train": "鬼灭之刃：无限列车篇",
  "demon slayer: entertainment district": "鬼灭之刃：游郭篇",
  "demon slayer: swordsmith village": "鬼灭之刃：刀匠村篇",
  "shingeki no kyojin": "进击的巨人",
  "attack on titan": "进击的巨人",
  "shingeki no kyojin: the final season": "进击的巨人 最终季",
  "attack on titan: the final season": "进击的巨人 最终季",
  "attack on titan final season": "进击的巨人 最终季",
  "attack on titan: the final season part 2": "进击的巨人 最终季 Part 2",
  "attack on titan: the final season - final chapters": "进击的巨人 最终季 完结篇",
  "shingeki no kyojin: the final season part 2": "进击的巨人 最终季 Part 2",
  "shingeki no kyojin: the final season - final chapters": "进击的巨人 最终季 完结篇",
  "jujutsu kaisen": "咒术回战",
  "jujutsu kaisen 0": "咒术回战0",
  "jujutsu kaisen 2nd season": "咒术回战 第二季",
  "jujutsu kaisen season 2": "咒术回战 第二季",
  "jujutsu kaisen: shibuya incident": "咒术回战 涉谷事变",
  "chainsaw man": "链锯人",
  "chainsaw man season 2": "链锯人 第二季",
  "spy x family": "间谍过家家",
  "spy family": "间谍过家家",
  "spy x family code: white": "间谍过家家 代号：白",
  "spy x family season 2": "间谍过家家 第二季",
  "spyfamily": "间谍过家家",
  "sousou no frieren": "葬送的芙莉莲",
  "frieren: beyond journey's end": "葬送的芙莉莲",
  "frieren": "葬送的芙莉莲",
  "kusuriya no hitorigoto": "药屋少女的呢喃",
  "the apothecary diaries": "药屋少女的呢喃",
  "the apothecary diaries season 2": "药屋少女的呢喃 第二季",
  "bocchi the rock!": "孤独摇滚",
  "bocchi the rock": "孤独摇滚",
  "lycoris recoil": "莉可丽丝",
  "mushoku tensei": "无职转生",
  "mushoku tensei: jobless reincarnation": "无职转生",
  "mushoku tensei ii": "无职转生 第二季",
  "mushoku tensei: jobless reincarnation season 2": "无职转生 第二季",
  "tokyo revengers": "东京复仇者",
  "tokyo revengers: tenjiku-hen": "东京复仇者 天竺篇",
  "tokyo revengers season 2": "东京复仇者 第二季",
  "tokyo revengers: christmas showdown": "东京复仇者 圣诞之箭篇",
  "youkoso jitsuryoku shijou shugi no kyoushitsu e": "欢迎来到实力至上主义教室",
  "classroom of the elite": "欢迎来到实力至上主义教室",
  "classroom of the elite 2nd season": "欢迎来到实力至上主义教室 第二季",
  "classroom of the elite season 2": "欢迎来到实力至上主义教室 第二季",
  "classroom of the elite season 3": "欢迎来到实力至上主义教室 第三季",
  "sword art online": "刀剑神域",
  "sword art online ii": "刀剑神域II",
  "sword art online: alicization": "刀剑神域 爱丽丝篇",
  "sword art online: alicization - war of underworld": "刀剑神域 爱丽丝篇 异界战争",
  "sword art online progressive": "刀剑神域 进击篇",
  "sao": "刀剑神域",
  "re:zero kara hajimeru isekai seikatsu": "Re:从零开始的异世界生活",
  "re:zero − starting life in another world": "Re:从零开始的异世界生活",
  "re:zero": "Re:从零开始的异世界生活",
  "re:zero season 2": "Re:从零开始的异世界生活 第二季",
  "re:zero season 3": "Re:从零开始的异世界生活 第三季",
  "tensei shitara slime datta ken": "关于我转生变成史莱姆这档事",
  "that time i got reincarnated as a slime": "关于我转生变成史莱姆这档事",
  "the time i got reincarnated as a slime": "关于我转生变成史莱姆这档事",
  "slime": "关于我转生变成史莱姆这档事",
  "tensura": "关于我转生变成史莱姆这档事",
  "fate/stay night": "Fate/stay night",
  "fate/stay night: unlimited blade works": "Fate/stay night UBW",
  "fate/zero": "Fate/Zero",
  "fate/grand order": "Fate/Grand Order",
  "fate/apocrypha": "Fate/Apocrypha",
  "fate/extra last encore": "Fate/Extra Last Encore",
  "fate/strange fake": "Fate/strange fake",
  "mahou shoujo madoka magica": "魔法少女小圆",
  "puella magi madoka magica": "魔法少女小圆",
  "madoka magica": "魔法少女小圆",
  "madoka magica: rebellion": "魔法少女小圆 叛逆的物语",
  "madoka magica movie 4": "魔法少女小圆 永远的物语",
  "violet evergarden": "紫罗兰永恒花园",
  "violet evergarden movie": "紫罗兰永恒花园 剧场版",
  "violet evergarden: the movie": "紫罗兰永恒花园 剧场版",
  "violet evergarden: eternity and the auto memory doll": "紫罗兰永恒花园 外传",
  "cells at work!": "工作细胞",
  "cells at work": "工作细胞",
  "hataraku saibou": "工作细胞",
  "cells at work!!": "工作细胞 第二季",
  "cells at work code black": "工作细胞BLACK",
  "kaguya-sama: love is war": "辉夜大小姐想让我告白",
  "kaguya-sama wa kokurasetai": "辉夜大小姐想让我告白",
  "kaguya-sama love is war": "辉夜大小姐想让我告白",
  "kaguya sama": "辉夜大小姐想让我告白",
  "kaguya-sama: love is war - ultra romantic": "辉夜大小姐想让我告白 -Ultra Romantic-",
  "kaguya-sama: love is war season 2": "辉夜大小姐想让我告白 第二季",
  "kaguya-sama: love is war season 3": "辉夜大小姐想让我告白 第三季",
  "go-toubun no hanayome": "五等分的新娘",
  "the quintessential quintuplets": "五等分的新娘",
  "go-toubun no hanayome∬": "五等分的新娘∬",
  "the quintessential quintuplets movie": "五等分的新娘 剧场版",
  "yuru camp": "摇曳露营△",
  "yuru camp△": "摇曳露营△",
  "yuru camp season 2": "摇曳露营△ 第二季",
  "laid-back camp": "摇曳露营△",
  "laid-back camp season 2": "摇曳露营△ 第二季",
  "seishun buta yarou": "青春猪头少年不会梦到兔女郎学姐",
  "rascal does not dream of bunny girl senpai": "青春猪头少年不会梦到兔女郎学姐",
  "rascal does not dream of a knapsack kid": "青春猪头少年不会梦到背包客女孩",
  "rascal does not dream of a sister venturing out": "青春猪头少年不会梦到出海的姐姐",
  "rascal does not dream of a dreaming girl": "青春猪头少年不会梦到怀梦美少女",
  "eighty-six": "86 -不存在的战区-",
  "86": "86 -不存在的战区-",
  "86: eighty-six": "86 -不存在的战区-",
  "86 eighty-six part 2": "86 -不存在的战区- 第二季",
  "cyberpunk: edgerunners": "赛博朋克：边缘行者",
  "suzume no tojimari": "铃芽之旅",
  "suzume": "铃芽之旅",
  "kimi no na wa": "你的名字。",
  "your name.": "你的名字。",
  "your name": "你的名字。",
  "tenki no ko": "天气之子",
  "weathering with you": "天气之子",
  "the place promised in our early days": "云的彼端，约定的地方",
  "5 centimeters per second": "秒速五厘米",
  "byousoku 5 centimeter": "秒速五厘米",
  "garden of words": "言叶之庭",
  "kotonoha no niwa": "言叶之庭",
  "spirited away": "千与千寻",
  "sen to chihiro no kamikakushi": "千与千寻",
  "howl's moving castle": "哈尔的移动城堡",
  "hauru no ugoku shiro": "哈尔的移动城堡",
  "my neighbor totoro": "龙猫",
  "tonari no totoro": "龙猫",
  "princess mononoke": "幽灵公主",
  "mononoke hime": "幽灵公主",
  "grave of the fireflies": "萤火虫之墓",
  "hotaru no haka": "萤火虫之墓",
  "castle in the sky": "天空之城",
  "tenkuu no shiro laputa": "天空之城",
  "kiki's delivery service": "魔女宅急便",
  "majo no takkyuubin": "魔女宅急便",
  "nausicaä of the valley of the wind": "风之谷",
  "kaze no tani no naushika": "风之谷",
  "ponyo": "崖上的波妞",
  "gake no ue no ponyo": "崖上的波妞",
  "the wind rises": "起风了",
  "kaze tachinu": "起风了",
  "the tale of the princess kaguya": "辉夜姬物语",
  "kaguyahime no monogatari": "辉夜姬物语",
  "arrietty": "借东西的小人阿莉埃蒂",
  "karigurashi no arrietty": "借东西的小人阿莉埃蒂",
  "when marnie was there": "回忆中的玛妮",
  "omoide no marnie": "回忆中的玛妮",
  "toradora!": "龙与虎",
  "toradora": "龙与虎",
  "clannad": "CLANNAD",
  "clannad: after story": "CLANNAD ~After Story~",
  "clannad after story": "CLANNAD ~After Story~",
  "golden time": "金色时光",
  "shigatsu wa kimi no uso": "四月是你的谎言",
  "your lie in april": "四月是你的谎言",
  "ano hi mita hana no namae wo bokutachi wa mada shiranai": "未闻花名",
  "anohana": "未闻花名",
  "koe no katachi": "声之形",
  "a silent voice": "声之形",
  "haikyuu!!": "排球少年",
  "haikyuu": "排球少年",
  "haikyuu!! to the top": "排球少年 到达顶点",
  "haikyuu!! season 4": "排球少年 第四季",
  "haikyuu movie": "排球少年 剧场版",
  "haikyuu!! the movie": "排球少年 剧场版",
  "blue lock": "蓝色监狱",
  "bluelock": "蓝色监狱",
  "blue lock season 2": "蓝色监狱 第二季",
  "ao ashi": "青之芦苇",
  "captain tsubasa": "足球小将",
  "slam dunk": "灌篮高手",
  "the first slam dunk": "灌篮高手THE FIRST SLAM DUNK",
  "kuroko's basketball": "黑子的篮球",
  "kuroko no basket": "黑子的篮球",
  "free!": "Free!",
  "free! - iwatobi swim club": "Free!",
  "yuri on ice": "冰上的尤里",
  "yuri!!! on ice": "冰上的尤里",
  "megalo box": "机甲拳击",
  "ashita no joe": "明日之丈",
  "hajime no ippo": "第一神拳",
  "initial d": "头文字D",
  "ping pong the animation": "乒乓",
  "overlord": "Overlord",
  "overlord season 2": "Overlord 第二季",
  "overlord season 3": "Overlord 第三季",
  "overlord season 4": "Overlord 第四季",
  "tate no yuusha no nariagari": "盾之勇者成名录",
  "the rising of the shield hero": "盾之勇者成名录",
  "the rising of the shield hero season 2": "盾之勇者成名录 第二季",
  "the rising of the shield hero season 3": "盾之勇者成名录 第三季",
  "konosuba": "为美好的世界献上祝福！",
  "kono suba": "为美好的世界献上祝福！",
  "kono subarashii sekai ni shukufuku wo!": "为美好的世界献上祝福！",
  "konosuba: god's blessing on this wonderful world!": "为美好的世界献上祝福！",
  "konosuba season 2": "为美好的世界献上祝福！ 第二季",
  "konosuba season 3": "为美好的世界献上祝福！ 第三季",
  "the saga of tanya the evil": "幼女战纪",
  "youjo senki": "幼女战纪",
  "no game no life": "游戏人生",
  "no game no life: zero": "游戏人生 零",
  "grimgar of fantasy and ash": "灰与幻想的格林姆迦尔",
  "hai to gensou no grimgar": "灰与幻想的格林姆迦尔",
  "the devil is a part-timer!": "打工吧！魔王大人",
  "hataraku maou-sama!": "打工吧！魔王大人",
  "the devil is a part-timer! season 2": "打工吧！魔王大人 第二季",
  "tsukimichi: moonlit fantasy": "月光下的异世界之旅",
  "tsukimichi": "月光下的异世界之旅",
  "campfire cooking in another world with my absurd skill": "拥有超常技能的异世界流浪美食家",
  "farming life in another world": "异世界悠闲农家",
  "the worlds finest assassin gets reincarnated in another world as an aristocrat": "世界顶尖的暗杀者转生为异世界贵族",
  "my dress-up darling": "更衣人偶坠入爱河",
  "sono bisque doll wa koi wo suru": "更衣人偶坠入爱河",
  "my dress-up darling season 2": "更衣人偶坠入爱河 第二季",
  "nisekoi": "伪恋",
  "nisekoi:": "伪恋 第二季",
  "oregairu": "我的青春恋爱物语果然有问题",
  "my youth romantic comedy is wrong, as i expected": "我的青春恋爱物语果然有问题",
  "my teen romantic comedy snafu": "我的青春恋爱物语果然有问题",
  "my youth romantic comedy is wrong, as i expected season 3": "我的青春恋爱物语果然有问题 第三季",
  "horimiya": "堀与宫村",
  "horimiya: the missing pieces": "堀与宫村 -piece-",
  "komi can't communicate": "古见同学有交流障碍症",
  "komi-san wa comyushou desu": "古见同学有交流障碍症",
  "don't toy with me, miss nagatoro": "不要欺负我，长瀞同学",
  "ijiranaide, nagatoro-san": "不要欺负我，长瀞同学",
  "nagatoro-san": "不要欺负我，长瀞同学",
  "tonikaku kawaii": "总之就是非常可爱",
  "fly me to the moon": "总之就是非常可爱",
  "wotakoi: love is hard for otaku": "宅男腐女恋爱真难",
  "wotaku ni koi wa muzukashiri": "宅男腐女恋爱真难",
  "love is war for otaku": "宅男腐女恋爱真难",
  "teasing master takagi-san": "擅长捉弄的高木同学",
  "karakai jouzu no takagi-san": "擅长捉弄的高木同学",
  "the angel next door spoils me rotten": "邻家的天使大人",
  "oshi no ko": "我推的孩子",
  "my star": "我推的孩子",
  "oshi no ko season 2": "我推的孩子 第二季",
  "kimini todoke": "好想告诉你",
  "from me to you": "好想告诉你",
  "a condition called love": "名为恋爱的疾病",
  "makeine: too many losing heroines!": "败犬女主太多了！",
  "too many losing heroines": "败犬女主太多了！",
  "tomo-chan is a girl": "Tomo-chan是女孩子！",
  "tomo-chan wa onnanoko!": "Tomo-chan是女孩子！",
  "shikimori's not just a cutie": "式守同学不只是可爱",
  "kawaii dake ja nai shikimori-san": "式守同学不只是可爱",
  "aharen-san wa hakarenai": "阿波连同学",
  "my love story!!": "俺物语!!",
  "ore monogatari!!": "俺物语!!",
  "rent-a-girlfriend": "租借女友",
  "kanokari": "租借女友",
  "kanojo, okarishimasu": "租借女友",
  "domestic girlfriend": "家有女友",
  "futoku no guild": "不道德的公会",
  "non non biyori": "悠哉日常大王",
  "k-on!": "轻音少女",
  "k-on": "轻音少女",
  "k-on!!": "轻音少女 第二季",
  "a place further than the universe": "比宇宙更远的地方",
  "sora yori mo tooi basho": "比宇宙更远的地方",
  "maid dragon": "小林家的龙女仆",
  "kobayashi-san chi no maid dragon": "小林家的龙女仆",
  "miss kobayashi's dragon maid": "小林家的龙女仆",
  "kobayashi-san chi no maid dragon s": "小林家的龙女仆S",
  "barakamon": "元气囝仔",
  "silver spoon": "银之匙",
  "gin no saji": "银之匙",
  "mushishi": "虫师",
  "natsume's book of friends": "夏目友人帐",
  "natsume yuujinchou": "夏目友人帐",
  "flying witch": "飞翔的魔女",
  "sweetness and lightning": "甜甜圈与蜜蜜",
  "amaama to inazuma": "甜甜圈与蜜蜜",
  "school babysitters": "学园奶爸",
  "gakuen babysitters": "学园奶爸",
  "the helpful fox senko-san": "贤惠幼妻仙狐小姐",
  "senryu girl": "川柳少女",
  "diary of our days at the breakwater": "海钓日记",
  "super cub": "超级小车",
  "death note": "死亡笔记",
  "monster": "怪物",
  "steins gate": "命运石之门",
  "steins;gate": "命运石之门",
  "steins;gate 0": "命运石之门0",
  "psycho-pass": "心理测量者",
  "psycho-pass season 2": "心理测量者 第二季",
  "psycho-pass 3": "心理测量者 第三季",
  "the promised neverland": "约定的梦幻岛",
  "yakusoku no neverland": "约定的梦幻岛",
  "the promised neverland season 2": "约定的梦幻岛 第二季",
  "odd taxi": "奇巧计程车",
  "erased": "只有我不在的街道",
  "boku dake ga inai machi": "只有我不在的街道",
  "paranoia agent": "妄想代理人",
  "mousou dairinin": "妄想代理人",
  "perfect blue": "未麻的部屋",
  "paprika": "红辣椒",
  "parasyte": "寄生兽",
  "kiseijuu": "寄生兽",
  "mirai nikki": "未来日记",
  "future diary": "未来日记",
  "higurashi when they cry": "寒蝉鸣泣之时",
  "higurashi no naku koro ni": "寒蝉鸣泣之时",
  "another": "Another",
  "code geass hangyaku no lelouch": "反叛的鲁路修",
  "code geass lelouch of the rebellion": "反叛的鲁路修",
  "code geass": "反叛的鲁路修",
  "code geass r2": "反叛的鲁路修R2",
  "code geass: rozé of the recapture": "反叛的鲁路修 夺还的Z",
  "cowboy bebop": "星际牛仔",
  "neon genesis evangelion": "新世纪福音战士",
  "evangelion": "新世纪福音战士",
  "evangelion: 3.0+1.0 thrice upon a time": "新·福音战士剧场版：终",
  "shin seiki evangelion": "新世纪福音战士",
  "gurren lagann": "天元突破",
  "tengen toppa gurren lagann": "天元突破",
  "akira": "阿基拉",
  "ghost in the shell": "攻壳机动队",
  "ghost in the shell: stand alone complex": "攻壳机动队 SAC",
  "stand alone complex": "攻壳机动队 SAC",
  "trigun": "枪神",
  "trigun stampede": "枪神 STAMPEDE",
  "serial experiments lain": "玲音",
  "lain": "玲音",
  "ergo proxy": "死亡代理人",
  "planetes": "星空清理者",
  "eureka seven": "交响诗篇",
  "gundam": "高达",
  "mobile suit gundam": "机动战士高达",
  "mobile suit gundam: the witch from mercury": "机动战士高达 水星的魔女",
  "gundam: the witch from mercury": "机动战士高达 水星的魔女",
  "suisei no gargantia": "翠星的加尔刚蒂亚",
  "gargantia on the verdurous planet": "翠星的加尔刚蒂亚",
  "vivy: fluorite eye's song": "Vivy -Fluorite Eye's Song-",
  "vivy fluorite eye's song": "Vivy -Fluorite Eye's Song-",
  "86 eighty-six": "86 -不存在的战区-",
  "one punch man": "一拳超人",
  "one punch man season 2": "一拳超人 第二季",
  "one punch man season 3": "一拳超人 第三季",
  "baki": "刃牙",
  "baki hanma": "范马刃牙",
  "kengan ashura": "拳愿阿修罗",
  "record of ragnarok": "终末的女武神",
  "shuumatsu no valkyrie": "终末的女武神",
  "dorohedoro": "ドロヘドロ",
  "dorohedoro season 2": "ドロヘドロ 第二季",
  "fire force": "炎炎消防队",
  "enen no shouboutai": "炎炎消防队",
  "soul eater": "噬魂师",
  "undead unluck": "不死不幸",
  "mashle": "肌肉魔法使",
  "mashle: magic and muscles": "肌肉魔法使",
  "mashle season 2": "肌肉魔法使 第二季",
  "hell's paradise": "地狱乐",
  "jigokuraku": "地狱乐",
  "kaiju no 8": "怪兽8号",
  "8 kaijuu": "怪兽8号",
  "kaijuu no. 8": "怪兽8号",
  "kaijuu 8-gou": "怪兽8号",
  "wind breaker": "防风铃",
  "windbreakers": "防风铃",
  "solo leveling": "我独自升级",
  "ore dake level up na ken": "我独自升级",
  "solo leveling season 2": "我独自升级 第二季",
  "dandadan": "蛋蛋蛋",
  "dan da dan": "蛋蛋蛋",
  "grand blue": "碧蓝之海",
  "grand blue dreaming": "碧蓝之海",
  "saiki kusuo no psi-nan": "齐木楠雄的灾难",
  "the disastrous life of saiki k.": "齐木楠雄的灾难",
  "daily lives of high school boys": "男子高中生的日常",
  "danshi koukousei no nichijou": "男子高中生的日常",
  "asobi asobase": "女高中生的虚度日常",
  "the way of the househusband": "极主夫道",
  "gokushufudou": "极主夫道",
  "haven't you heard? i'm sakamoto": "坂本日常",
  "sakamoto desu ga?": "坂本日常",
  "tanaka-kun is always listless": "田中君总是如此慵懒",
  "tanaka-kun wa itsumo kedaruge": "田中君总是如此慵懒",
  "nichijou": "日常",
  "lucky star": "幸运星",
  "lucky☆star": "幸运星",
  "azumanga daioh": "阿滋漫画大王",
  "pop team epic": "POP TEAM EPIC",
  "poputepipikku": "POP TEAM EPIC",
  "zombie land saga": "佐贺偶像是传奇",
  "zombie land saga revenge": "佐贺偶像是传奇 Revenge",
  "the great jahy will not be defeated!": "大魔女不会被打败！",
  "jahy-sama wa kujikenai!": "大魔女不会被打败！",
  "uzaki-chan wants to hang out!": "宇崎学妹想要玩",
  "uzaki-chan wa asobitai!": "宇崎学妹想要玩",
  "love live!": "Love Live!",
  "love live! school idol project": "Love Live!",
  "love live! sunshine!!": "Love Live! Sunshine!!",
  "love live! nijigasaki high school idol club": "Love Live! 虹咲学园学园偶像同好会",
  "love live! superstar!!": "Love Live! SuperStar!!",
  "the idolmaster": "偶像大师",
  "the idolmaster cinderella girls": "偶像大师 灰姑娘女孩",
  "shirobako": "白箱",
  "hibike! euphonium": "吹响！上低音号",
  "sound! euphonium": "吹响！上低音号",
  "given": "Given",
  "carole & tuesday": "卡萝尔与星期二",
  "macross delta": "超时空要塞Δ",
  "uma musume: pretty derby": "赛马娘",
  "uma musume pretty derby": "赛马娘",
  "uma musume": "赛马娘",
  "arknights: prelude to dawn": "明日方舟：黎明前奏",
  "arknights": "明日方舟",
  "blue archive": "蔚蓝档案",
  "genshin impact": "原神",
  "honkai star rail": "崩坏：星穹铁道",
  "girls' frontline": "少女前线",
  "azur lane": "碧蓝航线",
  "kantai collection": "舰队Collection",
  "kan colle": "舰队Collection",
  "fate grand order absolute demonic front babylonia": "Fate/Grand Order 绝对魔兽战线巴比伦尼亚",
  "sweetness & lightning": "甜甜圈与蜜蜜",
  "tokyo ghoul": "东京喰种",
  "tokyo ghoul √a": "东京喰种√A",
  "tokyo ghoul:re": "东京喰种:re",
  "berserk": "剑风传奇",
  "berserk: the golden age arc": "剑风传奇 黄金时代篇",
  "vinland saga": "冰海战记",
  "vinland saga season 2": "冰海战记 第二季",
  "made in abyss": "来自深渊",
  "made in abyss season 2": "来自深渊 烈日的黄金乡",
  "made in abyss: dawn of the deep soul": "来自深渊 深邃的魂之黎明",
  "promised neverland": "约定的梦幻岛",
  "beastars": "动物狂想曲",
  "beastars season 2": "动物狂想曲 第二季",
  "great pretender": "大欺诈师",
  "great pretender razbliuto": "大欺诈师 razbliuto",
  "dr. stone": "石纪元",
  "dr. stone season 2": "石纪元 第二季",
  "dr. stone: stone wars": "石纪元 石之战争",
  "dr. stone science future": "石纪元 SCIENCE FUTURE",
  "the worlds finest assassin": "世界顶尖的暗杀者",
  "mushoku tensei season 2": "无职转生 第二季",
  "campfire cooking in another world": "拥有超常技能的异世界流浪美食家",
  "welcome to demon school iruma-kun": "入间同学入魔了",
  "iruma-kun": "入间同学入魔了",
  "maou gakuin no futekigousha": "魔王学院的不适合者",
  "the misfit of demon king academy": "魔王学院的不适合者",
  "in another world with my smartphone": "带着智能手机闯荡异世界",
  "isekai wa smartphone to tomo ni": "带着智能手机闯荡异世界",
  "how not to summon a demon lord": "异世界魔王与召唤少女的奴隶魔术",
  "death march to the parallel world rhapsody": "异世界居酒屋",
  "kumo desu ga, nani ka?": "转生成蜘蛛又怎样",
  "so i'm a spider, so what?": "转生成蜘蛛又怎样",
  "the Saint's Magic Power is Omnipotent": "圣女的魔力是万能的",
  "seija no chikara": "圣女的魔力是万能的",
  "high school dxd": "恶魔高校DxD",
  "to love-ru": "To LOVE",
  "to love ru": "To LOVE",
  "testament of sister new devil": "新妹魔王的契约者",
  "shinmai maou no testament": "新妹魔王的契约者",
  "prison school": "监狱学园",
  "kangoku gakuen": "监狱学园",
  "kill la kill": "斩服少女",
  "shimoneta": "下流梗不存在的灰暗世界",
  "food wars": "食戟之灵",
  "shokugeki no soma": "食戟之灵",
  "shokugeki no soma season 2": "食戟之灵 第二季",
  "shokugeki no soma season 3": "食戟之灵 第三季",
  "we never learn": "我们无法一起学习",
  "bokutachi wa benkyou ga dekinai": "我们无法一起学习",
  "giji harem": "伪恋",
  "kingdom": "王者天下",
  "kingdom season 2": "王者天下 第二季",
  "kingdom season 3": "王者天下 第三季",
  "kingdom season 4": "王者天下 第四季",
  "legend of the galactic heroes": "银河英雄传说",
  "ginga eiyuu densetsu": "银河英雄传说",
  "the heroic legend of arslan": "亚尔斯兰战记",
  "arslan senki": "亚尔斯兰战记",
  "gate": "GATE 奇幻自卫队",
  "gate: jieitai kanochi nite, kaku tatakaeri": "GATE 奇幻自卫队",
  "warlords of sigdrifa": "战翼的西格德莉法",
  "senyoku no sigfrid": "战翼的西格德莉法",
  "i want to eat your pancreas": "我想吃掉你的胰脏",
  "kimi no suizou wo tabetai": "我想吃掉你的胰脏",
  "a whisker away": "想哭的我戴上了猫的面具",
  "nakitai watashi wa nezumi wo kaburu": "想哭的我戴上了猫的面具",
  "fireworks": "烟花",
  "uchiage hanabi": "烟花",
  "the boy and the heron": "你想活出怎样的人生",
  "kimitachi wa dou ikiru ka": "你想活出怎样的人生",
  "one piece film red": "海贼王 FILM RED",
  "one piece film: red": "海贼王 FILM RED",
  "dragon ball super: broly": "龙珠超 布罗利",
  "dragon ball super: super hero": "龙珠超 超级英雄",
  "my hero academia: two heroes": "我的英雄学院 两位英雄",
  "my hero academia: heroes rising": "我的英雄学院 HEROES RISING",
  "my hero academia: world heroes' mission": "我的英雄学院 WORLD HEROES' MISSION",
  "fate/stay night: heaven's feel": "Fate/stay night Heaven's Feel",
  "fate stay night heavens feel": "Fate/stay night Heaven's Feel",
  "sword art online: ordinal scale": "刀剑神域 序列之争",
  "konosuba: legend of crimson": "为美好的世界献上祝福！ 红传说",
  "the anthem of the heart": "心灵想要大声呼喊",
  "kokoro ga sakebitagatterunda": "心灵想要大声呼喊",
  "maquia: when the promised flower blooms": "朝花夕誓",
  "sayonara no asa ni yakusoku no hana wo kazarou": "朝花夕誓",
  "liz and the blue bird": "莉兹与青鸟",
  "liz to aoi tori": "莉兹与青鸟",
  "tamako love story": "玉子爱情故事",
  "the disappearance of haruhi suzumiya": "凉宫春日的消失",
  "suzumiya haruhi no shoushitsu": "凉宫春日的消失",
  "kizumonogatari": "伤物语",
  "kizumonogatari iii: cold blooded": "伤物语 冷血篇",
  "fate/grand order - absolute demonic front: babylonia": "Fate/Grand Order 绝对魔兽战线巴比伦尼亚",
  "the garden of sinners": "空之境界",
  "kara no kyoukai": "空之境界",
  "wolf children": "狼的孩子雨和雪",
  "ookami kodomo no ame to yuki": "狼的孩子雨和雪",
  "summer wars": "夏日大作战",
  "the girl who leapt through time": "穿越时空的少女",
  "toki wo kakeru shoujo": "穿越时空的少女",
  "millennium actress": "千年女优",
  "sennen joyuu": "千年女优",
  "tokyo godfathers": "东京教父",
  "jin-roh": "人狼",
  "jinrou": "人狼",
  "patema inverted": "颠倒的帕特玛",
  "sakasama no patema": "颠倒的帕特玛",
  "children who chase lost voices": "追逐繁星的孩子",
  "hoshi wo ou kodomo": "追逐繁星的孩子",
  "angel beats!": "Angel Beats!",
  "angel beats": "Angel Beats!",
  "charlotte": "Charlotte",
  "plastic memories": "可塑性记忆",
  "ranking of kings": "国王排名",
  "ousama ranking": "国王排名",
  "vermeil in gold": "金装的维尔梅",
  "kinsou no vermeil": "金装的维尔梅",
  "love after world domination": "世界征服后的恋爱",
  "skip and loafer": "斯·基普与乐福",
  "skip to loafer": "斯·基普与乐福",
  "heavenly delusion": "天国大魔境",
  "tengoku daimakyou": "天国大魔境",
  "dangers in my heart": "我心里危险的东西",
  "boku no kokoro no yabai yatsu": "我心里危险的东西",
  "shangri-la frontier": "香格里拉边境",
  "zom 100: bucket list of the dead": "僵尸100",
  "zom 100": "僵尸100",
  "the ice guy and his cool female colleague": "冰属性男子与酷酷女同事",
  "ice guy": "冰属性男子与酷酷女同事",
  "my happy marriage": "我的幸福婚约",
  "watashi no shiawase na kekkon": "我的幸福婚约",
  "my happy marriage season 2": "我的幸福婚约 第二季",
  "sugar apple fairy tale": "糖苹果 Fairy Tale",
  "sugar apple": "糖苹果 Fairy Tale",
  "the dangers in my heart": "我心里危险的东西",
  "blue period": "蓝色时期",
  "the aquatope on white sand": "白砂的水族馆",
  "shiroi suna no aquatope": "白砂的水族馆",
  "sonny boy": "Sonny Boy",
  "wonder egg priority": "奇蛋物语",
  "id:invaded": "异度侵入",
  "eizouken ni wa te wo dasu na!": "别对映像研出手！",
  "keep your hands off eizouken!": "别对映像研出手！",
  "hoozuki no reitetsu": "鬼灯的冷彻",
  "kono oto tomare!": "弦音-风舞高中弓道部",
  "sound of life": "弦音-风舞高中弓道部",
  "banana fish": "Banana Fish",
  "megalo box 2: nomad": "机甲拳击2 NOMAD",
  "to your eternity": "致不灭的你",
  "fumetsu no anata e": "致不灭的你",
  "to your eternity season 2": "致不灭的你 第二季",
  "takt op. destiny": "takt op.Destiny",
  "takt op destiny": "takt op.Destiny",
  "visual prison": "Visual Prison",
  "mieruko-chan": "看得见的女孩",
  "the detective is already dead": "侦探已死",
  "tantei wa mou, shindeiru.": "侦探已死",
  "remake our life": "我们的重制人生",
  "bokutachi no remake": "我们的重制人生",
  "higehiro": "剃须。然后捡到女高中生。",
  "higehiro: after being rejected, i shaved and took in a high school runaway": "剃须。然后捡到女高中生。",
  "osamake": "女朋友 and 女朋友",
  "kanojo mo kanojo": "女朋友 and 女朋友",
  "girlfriend girlfriend": "女朋友 and 女朋友",
  "my stepmom's daughter is my ex": "继母的拖油瓶是我的前女友",
  "mamahaha no tsurego ga motokano datta": "继母的拖油瓶是我的前女友",
  "the maid I hired recently is mysterious": "最近雇的女仆有点怪",
  "saikin yatotta meido ga ayashii": "最近雇的女仆有点怪",
  "call of the night": "彻夜之歌",
  "yofukashi no uta": "彻夜之歌",
  "engage kiss": "契约之吻",
  "prima doll": "Primadoll",
  "lass reine": "Lass Reine",
  "the yakuza's guide to babysitting": "极道主夫",
  "kumichou musume to sewagakari": "极道主夫",
  "sumertime rendering": "夏日重现",
  "summertime render": "夏日重现",
  "fuuto tantei": "风都侦探",
  "windswept detective": "风都侦探",
  "heroine tarumono!": "成为女主角!",
  "heroine tarumono": "成为女主角!",
  "love live superstar": "Love Live! SuperStar!!",
  "akebi's sailor服": "明日酱的水手服",
  "akebi-chan no sailor-fuku": "明日酱的水手服",
  "the world's finest assassin gets reincarnated in another world as an aristocrat": "世界顶尖的暗杀者转生为异世界贵族",
  "sekai saikou no ansatsushia, isekai kizoku ni tensei suru": "世界顶尖的暗杀者转生为异世界贵族",
  "reincarnated as a sword": "转生成为魔剑",
  "tensei shitara ken deshita": "转生成为魔剑",
  "the strongest sage with the weakest crest": "最弱的驯兽师开始了捡垃圾之旅",
  "shikkakumon no saikyou kenja": "最弱的驯兽师开始了捡垃圾之旅",
  "skeleton knight in another world": "骸骨骑士大人异世界冒险中",
  "gaikotsu kishi-sama": "骸骨骑士大人异世界冒险中",
  "black summoner": "黑之召唤士",
  "harem in the labyrinth of another world": "异世界迷宫里的后宫生活",
  "isekai meikyuu de harem wo": "异世界迷宫里的后宫生活",
  "more than a married couple, but not lovers": "恋上换装娃娃",
  "fuufu ijou, koibito miman": "恋上换装娃娃",
  "trapped in a dating sim: the world of otome games is tough for mobs": "乙女游戏世界对路人角色很不友好",
  "otome game sekai wa mob ni kibishii sekai desu": "乙女游戏世界对路人角色很不友好",
  "the executioner and her way of life": "处刑少女的生存之道",
  "shokei shoujo no virgin road": "处刑少女的生存之道",
  "dance dance danseur": "舞动不止",
  "deaimon": "相遇之后",
  "onipan!": "鬼裤衩!",
  "in the heart of kunoichi tsubaki": "忍者之心",
  "kunoichi tsubaki no mune no uchi": "忍者之心",
  "estab-life: great escape": "Estab-Life",
  "komi can't communicate season 2": "古见同学有交流障碍症 第二季",
  "don't toy with me, miss nagatoro 2nd attack": "不要欺负我，长瀞同学 第二季",
  "nagatoro 2nd attack": "不要欺负我，长瀞同学 第二季",
  "teasing master takagi-san season 3": "擅长捉弄的高木同学 第三季",
  "karakai jouzu no takagi-san 3": "擅长捉弄的高木同学 第三季",
  "a couple of cuckoos": "杜鹃的婚约",
  "kakkou no Iinazuka": "杜鹃的婚约",
  "rent-a-girlfriend season 2": "租借女友 第二季",
  "kanojo, okarishimasu season 2": "租借女友 第二季",
  "rent-a-girlfriend season 3": "租借女友 第三季",
  "uzaki-chan wants to hang out! season 2": "宇崎学妹想要玩 第二季",
  "tsuredure children": "徒然喜欢你",
  "gamers!": "GAMERS 电玩咖！",
  "love chuunibyou & other delusions": "中二病也要谈恋爱！",
  "chuunibyou demo koi ga shitai!": "中二病也要谈恋爱！",
  "tamako market": "玉子市场",
  "baka and test": "笨蛋·测验·召唤兽",
  "baka to test to shoukanjuu": "笨蛋·测验·召唤兽",
  "working!!": "迷糊餐厅",
  "wagnaria!!": "迷糊餐厅",
  "hataraku maou-sama! season 2": "打工吧！魔王大人 第二季",
  "my mental choices are totally interfering with my school romantic comedy": "我的脑内恋碍选项",
  "noucome": "我的脑内恋碍选项",
  "invaders of the rokujouma!?": "六花的勇者",
  "rokujouma no shinryakusha!?": "六花的勇者",
  "engaged to the unidentified": "未确认进行时",
  "mikakunin de shinkoukei": "未确认进行时",
  "recently, my sister is unusual": "最近，妹妹的样子有点怪",
  "saikin, imouto no yousu ga chotto okashiinda ga": "最近，妹妹的样子有点怪",
  "if her flag breaks": "如果她的旗帜被折断了",
  "kanojo ga flag wo oraretara": "如果她的旗帜被折断了",
  "one week friends": "一周的朋友",
  "isshuukan friends": "一周的朋友",
  "my little monster": "邻座的怪同学",
  "tonari no kaibutsu-kun": "邻座的怪同学",
  "say i love you": "只要你说你爱我",
  "sukitte ii na yo": "只要你说你爱我",
  "kimi ni todoke": "好想告诉你",
  "kimi ni todoke season 2": "好想告诉你 第二季",
  "special a": "S.A 特优生",
  "special a class": "S.A 特优生",
  "maid sama": "会长是女仆大人",
  "kaichou wa maid-sama!": "会长是女仆大人",
  "ouran high school host club": "樱兰高校男公关部",
  "kamisama hajimemashita": "元气少女缘结神",
  "kamisama kiss": "元气少女缘结神",
  "akatsuki no yona": "晨曦公主",
  "yona of the dawn": "晨曦公主",
  "snow white with the red hair": "赤发白雪姬",
  "akagami no shirayuki-hime": "赤发白雪姬",
  "lovely complex": "恋爱情结",
  "love com": "恋爱情结",
  "little busters!": "Little Busters!",
  "little busters refrain": "Little Busters! Refrain",
  "kanon": "Kanon",
  "air": "Air",
  "sakurasou no pet na kanojo": "樱花庄的宠物女孩",
  "the pet girl of sakurasou": "樱花庄的宠物女孩",
  "ano natsu de matteru": "在盛夏等待",
  "waiting in the summer": "在盛夏等待",
  "kokoro connect": "心灵链环",
  "reLife": "ReLIFE",
  "re:life": "ReLIFE",
  "just because!": "Just Because!",
  "tsuki ga kirei": "月色真美",
  "as the moon, so beautiful": "月色真美",
  "sing yesterday for me": "昨日之歌",
  "yesterday wo utatte": "昨日之歌",
  "hokago teibou nisshi": "海钓日记",
  "non non biyori repeat": "悠哉日常大王 Repeat",
  "k-on! movie": "轻音少女 剧场版",
};

// Normalize title for matching
function normalize(str: string): string {
  return str.toLowerCase().trim()
    .replace(/[：:！!？?。.~\-–—''「」『』（）()☆★♪♫♬/\\,，。！？；;·•【】]/g, " ")
    .replace(/[[\]]/g, " ")
    .replace(/\s+/g, " ").trim();
}

// Build normalized lookup map
const NORMALIZED_MAP: Record<string, string> = {};
for (const [key, value] of Object.entries(TITLE_MAP)) {
  NORMALIZED_MAP[normalize(key)] = value;
}

// Reverse map: Chinese title -> romaji/English keyword for API search
const REVERSE_MAP: Record<string, string> = {};
for (const [key, value] of Object.entries(TITLE_MAP)) {
  const normValue = normalize(value);
  if (!REVERSE_MAP[normValue]) {
    REVERSE_MAP[normValue] = key;
  }
}

// Translate Chinese query to romaji/English for API search
export function translateSearchQuery(query: string): string {
  const norm = normalize(query);
  // Exact match
  if (REVERSE_MAP[norm]) return REVERSE_MAP[norm];
  // Partial match
  for (const [cn, en] of Object.entries(REVERSE_MAP)) {
    if (norm.includes(cn) || cn.includes(norm)) {
      return en;
    }
  }
  // No match, return original
  return query;
}

// Get Chinese display title for an anime
export function getChineseTitle(
  title: string,
  titleEnglish?: string | null,
  titleJapanese?: string | null
): string {
  const normTitle = normalize(title);
  if (NORMALIZED_MAP[normTitle]) return NORMALIZED_MAP[normTitle];

  if (titleEnglish) {
    const normEn = normalize(titleEnglish);
    if (NORMALIZED_MAP[normEn]) return NORMALIZED_MAP[normEn];
  }

  if (titleJapanese) {
    const normJp = normalize(titleJapanese);
    if (NORMALIZED_MAP[normJp]) return NORMALIZED_MAP[normJp];
  }

  // Try partial match
  for (const [key, value] of Object.entries(NORMALIZED_MAP)) {
    if (normTitle.includes(key) || key.includes(normTitle)) {
      return value;
    }
  }

  if (titleEnglish) {
    const normEn = normalize(titleEnglish);
    for (const [key, value] of Object.entries(NORMALIZED_MAP)) {
      if (normEn.includes(key) || key.includes(normEn)) {
        return value;
      }
    }
  }

  // Fallback: prefer Japanese (kanji readable by Chinese) > English > romaji
  return titleJapanese || titleEnglish || title;
}
